exports.HISTORIQUE_COMMANDE_PHARMACIE = 'histCmdPhar'
exports.COMMANDES_ENCOURS_PHARMACIE = 'cmdMtn'
exports.MEDICAMENTS_PHARMACIE = 'mesMed'
exports.AJOUTER_MEDICAMENT = 'nvMed'

exports.HISTORIQUE_COMMANDE_MEDECIN = 'histCmdDoc'
exports.MES_PATIENTS = 'mesPtn'
exports.NOUVEAU_PATIENT = 'nvPtn'
exports.NOUVELLE_COMMANDE_MEDECIN = 'nvlCmdDoc'

exports.MES_COMMANDES_PATIENT = 'mesCmd'
exports.NOUVELLE_COMMANDE_PATIENT = 'nvlCmd'
exports.CATALOGUE_MEDICAMENTS = 'ctlg'
exports.TROUVER_PHARMACIE_CARTE = 'pharmap'

exports.HISTORIQUE_COMMANDE_LIVREUR = 'histCmd'
exports.COMMANDES_ENCOURS_LIVREUR = 'liv'