exports.HISTORIQUE_COMMANDE_PHARMACIE = 'histCmdPhar'
exports.COMMANDES_ENCOURS_PHARMACIE = 'cmdMtn'
exports.MEDICAMENTS_PHARMACIE = 'mesMed'
exports.AJOUTER_MEDICAMENT = 'nvMed'

exports.HISTORIQUE_COMMANDE_MEDECIN = 'histCmdDoc'
exports.MES_PATIENTS = 'mesPtn'